version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - URL_PREFEITO=${URL_PREFEITO}
      - URL_VEREADORES=${URL_VEREADORES}

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker_service
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - api
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - URL_PREFEITO=${URL_PREFEITO}
      - URL_VEREADORES=${URL_VEREADORES}

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat_service
    command: celery -A celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - api
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_NAME=${DATABASE_NAME}
      - URL_PREFEITO=${URL_PREFEITO}
      - URL_VEREADORES=${URL_VEREADORES}